"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import os
import shutil

from setuptools import setup

if os.path.exists('build'):
    shutil.rmtree('build')

if os.path.exists('dist/Hostly.app'):
    shutil.rmtree('dist/Hostly.app')

APP = ['src/hostly.py']
DATA_FILES = [
    'portal' # ReactJS Application
]
OPTIONS = {
    'argv_emulation': False,
    'strip': True,
    'packages': [
        'asyncio_dgram',
        'bcrypt',
        'boto3',
        'botocore',
        'certifi',
        'cffi',
        'charset_normalizer',
        'click',
        'cryptography',
        'dns',
        'fabric',
        'flask',
        'idna',
        'importlib_metadata',
        'invoke',
        'itsdangerous',
        'jinja2',
        'jmespath',
        'markupsafe',
        'mcstatus',
        'mscli',
        'paramiko',
        'pathlib2',
        'proxy_tools',
        'pycparser',
        'nacl',
        'pysftp',
        'dateutil',
        'webview',
        'requests',
        's3transfer',
        'six',
        'urllib3',
        'werkzeug',
        'zipp'
    ],
    'iconfile': 'public/icons/logo.icns',
}

setup(
    name='Hostly',
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
